services:
  bookapi:
    image: ${DOCKER_REGISTRY-}bookapi
    build:
      context: .
      dockerfile: BookAPI/Dockerfile
    container_name: app
    depends_on:
    - postgres
    - redis 
    networks:
    - app

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: postgres_db
    networks:
      - app
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_book_data:/var/lib/postgresql/data
    
  redis:
    image: redis
    container_name: cache_redis
    networks:
      - app
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

networks:
  app:
  
volumes:
  pg_book_data:
  redis-data: